name: Integration Tests

on: [workflow_dispatch]

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run Frontend app on localhost
        run: |
          cd ./Code
          npm install
          npm start &
          sleep 5
      - name: Run Selenium test suite
        run: |
          cd ./Tests
          dotnet test --logger trx
      - name: Upload test result artifact for records
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: ./Tests/TestResults
